#include <iostream>
#include <bits/stdc++.h> // this library gives us access to all c++ library functions and we don't need to add other libraries seperately
using namespace std;

void delay_function(int number_of_seconds) // this function is just for making the printing look cool and interesting as it adds some delay in the output
{
    int milli_seconds = 1000 * number_of_seconds; 
  
    clock_t start_time = clock();  
    while (clock() < start_time + milli_seconds) {}
} 

int random_number_generator() // this function generates a random number for the each dice
{
	srand(static_cast<unsigned int>(time(nullptr))); // this is used to generate a new random number based on the time of the computer
	int new_number = 0;
	const int min_number = 1; // our minimum munber can be 1 on a dice
	const int max_number = 6; // our maximum number can be 6 on a dice
	new_number = (rand() % (max_number + 1 - min_number)) + min_number; // this generates a number between 1 and 6 both inclusive
	return new_number;
}

int main()
{
	int dice_1_num; // this stores the number generated by random generator for dice 1
	int dice_2_num; // this stores the number generated by random generator for dice 2
	int dice_3_num; // this stores the number generated by random generator for dice 3
	int option = -1, bet_amount = 0, i = 1;
	int credits = 100; // initially each user has 100 credits

	cout<<"Press 1 if you would like to bet?"<<endl;
	cout<<"Press 0 to Quit"<<endl;
	cin>>option;
	cout<<endl;

	while (credits != 0 || option != 0) // this loop runs until the user credits are == 0 or user enters 0 to quit the game
	{
		while (option != 0 && option != 1) // this while loop runs until the user enters 1 or 0 for respective choice
		{
			if (option != 0 && option != 1)
			{
				cout<<"Incorrect input!!!!!"<<endl<<endl;
			}
			cout<<"Reselect option..."<<endl;
			cout<<"Press 1 if you would like to bet?"<<endl;
			cout<<"Press 0 to Quit"<<endl;
			cin>>option;
			cout<<endl;
		}

		if (option == 0) // if user enters 0 then quit the game
		{
			cout<<"Leaving the Game"<<endl;
		}

		else if (option == 1) // if user wants to make a bet then ask for the bet amount
		{
			system("CLS"); // this command is just so that for each round our screen is made new so that we don't ahave too much unnecessary information on our screen
			cout<<"*******"<<endl;
			cout<<"ROUND "<<i<<endl;
			cout<<"*******"<<endl<<endl;
			i++;

			cout<<"----------------------------"<<endl;
			cout<<"Current Credits: "<<credits<<endl;
			cout<<"----------------------------"<<endl<<endl;

			if (credits == 0) // if the credits are 0 then return
			{
				cout<<"You dont have enough credits to continue..."<<endl;
				cout<<"Quiting!!!"<<endl;
				return 0;
			}

			else
			{
				cout<<"Enter the amount you want to bet: "; // ask user to enter the bet amount
				cin>>bet_amount;

				if (bet_amount == 0 || bet_amount > credits || bet_amount < 0) // if the user entered bet amount is 0 or user entered bet amount is negative or user entered bet amount is greater than the current credits of user
				{
					while (bet_amount == 0 || bet_amount > credits || bet_amount < 0) // this while loop runs until the user enters bet amount less than or equal to current credits or not equal to 0 or non negative
					{
						if (bet_amount == 0 || bet_amount > credits || bet_amount < 0)
						{
							cout<<"Please enter a non-neagtive, non 0 amount greater than or equal to your current credits!!"<<endl<<endl;
						}

						cout<<"Enter the amount you want to bet: ";
						cin>>bet_amount;
					}	
				}
				cout<<endl;
				credits = credits - bet_amount; // subtract the bet amount from the total credits of the player

				cout<<"Throwing the dice on the table... GOOD LUCK!!!"<<endl;

				int dice_num_sum = dice_1_num + dice_2_num + dice_3_num;
				dice_1_num = random_number_generator(); // assign random numbers between 1-6 to dice 1
				delay_function(1.2); // these delay functions are just for shashka purposes to make the output a bit engaging 
				dice_2_num = random_number_generator(); // assign random numbers between 1-6 to dice 2
				delay_function(1.2);
				dice_3_num = random_number_generator(); // assign random numbers between 1-6 to dice 3
				delay_function(1);
				cout<<".  ";
				delay_function(1);
				cout<<".  ";
				delay_function(1);
				cout<<".  "<<endl<<endl;
				cout<<"Dice 1 number: "<<dice_1_num<<endl;
				cout<<"Dice 2 number: "<<dice_2_num<<endl;
				cout<<"Dice 3 number: "<<dice_3_num<<endl<<endl;

				if (dice_1_num == 1 && dice_2_num == 1 && dice_3_num == 1) // all 3 dice show a 1
				{
					cout<<"You Won 30 times your bet amount!!"<<endl;
					credits = credits + bet_amount + (30*bet_amount);
				}
				else if ((dice_1_num != 1 && dice_2_num != 1 && dice_3_num != 1) && (dice_1_num == dice_2_num && dice_1_num == dice_3_num && dice_2_num == dice_3_num)) // if all three dice dont show 1 and show same value otherwise
				{
					cout<<"You Won 20 times your bet amount!!"<<endl;
					credits = credits + bet_amount + (20*bet_amount);
				}
				else if (dice_1_num == dice_2_num || dice_1_num == dice_3_num || dice_2_num == dice_3_num) // if 2 dice show same value and the third show a differnet value
				{
					cout<<"You Won 6 times your bet amount!!"<<endl;
					credits = credits + bet_amount + (6*bet_amount);
				}
				else if (dice_num_sum >= 15) // the total of the three dice come to 15 or more
				{
					cout<<"You Won 2 times your bet amount!!"<<endl;
					credits = credits + bet_amount + (2*bet_amount);
				}
				else if ((dice_1_num == 6 || dice_2_num == 6 || dice_3_num == 6) || ((dice_1_num % 2 != 0) && (dice_2_num % 2 != 0) && (dice_3_num % 2 != 0))) // If one dice shows a 6, or all the values of the dice are odd numbers
				{
					cout<<"You havent won anything, but you get your Bet Amount back!!"<<endl;
					credits = credits + bet_amount; 
				}
				else
				{
					credits = credits;
				}
			}

			cout<<"----------------------------"<<endl;
			cout<<"Updated Credits: "<<credits<<endl;
			cout<<"----------------------------"<<endl<<endl;
		}

		// after each round ask the user if they want to play or not, if yes then repeat the above process, else break the loop and quit the game 
		cout<<endl;
		cout<<"Press 1 if you would like to bet AGAIN?"<<endl;
		cout<<"Press 0 to Quit"<<endl;
		cin>>option;
		cout<<endl;
		if (option == 0)
		{
			cout<<"You chose to Quit the Game!"<<endl<<endl;
			cout<<"GOOD BYE...."<<endl<<endl;
			break;
		}
	}

	return 0;
}